### ISSUE TITLE
Upgrade to python 3

### ISSUE THREAD

**Issue by sulheim** [PriceLab/probannopy#2]
It seems like probannopy is only compatible with python 2, at least running `pip install -r requirements` failed with python 3, but worked fine with python 2.7. 

I imagine that only small changes to the source code are necessary to make it compatible with python 3. Optionally, make it clear in the README what the recommended python version is.

**Comment by kingb12** [comment]
Thanks for the input! For now I've added a note about this. With the end of support coming for python 2.x, I agree an update to python3 is important and shouldn't be particularly difficult. I'll leave this issue open for now until we have a python3 upgrade in place. Thanks!

**Comment by kingb12** [comment]
Should be resolved now with your PR, thanks! Let me know if you run into issues
